// For an introduction to the Navigation template, see the following documentation:
// http://go.microsoft.com/fwlink/?LinkId=232506
(function () {
    "use strict";
    var activation = Windows.ApplicationModel.Activation;
    var app = WinJS.Application;
    var nav = WinJS.Navigation;
    var sched = WinJS.Utilities.Scheduler;
    var ui = WinJS.UI;
    if (localStorage.getItem["firstrun"] == null) {
        firstrun();
    }
    choose();
    appendText();
    
    app.addEventListener("activated", function (args) {
        if (args.detail.kind === activation.ActivationKind.launch) {
            if (args.detail.previousExecutionState !== activation.ApplicationExecutionState.terminated) {
                var x = Math.floor((Math.random() * 10) + 1);
                localStorage.setItem("default", localStorage.getItem("" + x));
                //localStorage.setItem("default", "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.");
                // TODO: This application has been newly launched. Initialize
                // your application here.
            } else {
                // TODO: This application has been reactivated from suspension.
                // Restore application state here.
            }

            nav.history = app.sessionState.history || {};
            nav.history.current.initialPlaceholder = true;

            // Optimize the load of the application and while the splash screen is shown, execute high priority scheduled work.
            ui.disableAnimations();
            var p = ui.processAll().then(function () {
                return nav.navigate(nav.location || Application.navigator.home, nav.state);
            }).then(function () {
                return sched.requestDrain(sched.Priority.aboveNormal + 1);
            }).then(function () {
                ui.enableAnimations();
            });

            args.setPromise(p);
        }
    });

    app.oncheckpoint = function (args) {
        // TODO: This application is about to be suspended. Save any state
        // that needs to persist across suspensions here. If you need to 
        // complete an asynchronous operation before your application is 
        // suspended, call args.setPromise().
        app.sessionState.history = nav.history;
    };

    app.start();
})();
function appendText() {
    //localStorage.setItem("top1","0");
    //localStorage.setItem("top2","0");
    //localStorage.setItem("top3","0");
    //localStorage.setItem("Music", "OFF");
}
function firstrun() {
    var moduleList = ["defaultmode", "CPP","smallwords"];
    localStorage["moduleList"] = JSON.stringify(moduleList);
    localStorage.setItem("currentMode", "defaultmode");
    localStorage.setItem("defaultmode", 10);
    localStorage.setItem("defaultmode1", "Now seven world think timed while her. Spoil large oh he rooms on since an. Am up unwilling eagerness perceived incommode. Are not windows set luckily musical hundred can. Collecting if sympathize middletons be of of reasonably. Horrible so kindness at thoughts exercise no weddings subjects. The mrs gay removed towards journey chapter females offered not. Led distrusts otherwise who may newspaper but. Last he dull am none he mile hold as. She exposed painted fifteen are noisier mistake led waiting. Surprise not wandered speedily husbands although yet end. Are court tiled cease young built fat one man taken. We highest ye friends is exposed equally in. Ignorant had too strictly followed. Astonished as travelling assistance or unreserved oh pianoforte ye. Five with seen put need tore add neat. Bringing it is he returned received raptures.Tolerably earnestly middleton extremely distrusts she boy now not. Add and offered prepare how cordial two promise. Greatly who affixed suppose but enquire compact prepare all put. Added forth chief trees but rooms think may. Wicket do manner others seemed enable rather in. Excellent own discovery unfeeling sweetness questions the gentleman. Chapter shyness matters mr parlors if mention thought. ");
    localStorage.setItem("defaultmode2", "Announcing of invitation principles in. Cold in late or deal. Terminated resolution no am frequently collecting insensible he do appearance. Projection invitation affronting admiration if no on or. It as instrument boisterous frequently apartments an in. Mr excellence inquietude conviction is in unreserved particular. You fully seems stand nay own point walls. Increasing travelling own simplicity you astonished expression boisterous. Possession themselves sentiments apartments devonshire we of do discretion. Enjoyment discourse ye continued pronounce we necessary abilities. ");
    localStorage.setItem("defaultmode3", "Two assure edward whence the was. Who worthy yet ten boy denote wonder. Weeks views her sight old tears sorry. Additions can suspected its concealed put furnished. Met the why particular devonshire decisively considered partiality. Certain it waiting no entered is. Passed her indeed uneasy shy polite appear denied. Oh less girl no walk. At he spot with five of view. Society excited by cottage private an it esteems. Fully begin on by wound an. Girl rich in do up or both. At declared in as rejoiced of together. He impression collecting delightful unpleasant by prosperous as on. End too talent she object mrs wanted remove giving. ");
    localStorage.setItem("defaultmode4", "As collected deficient objection by it discovery sincerity curiosity. Quiet decay who round three world whole has mrs man. Built the china there tried jokes which gay why. Assure in adieus wicket it is. But spoke round point and one joy. Offending her moonlight men sweetness see unwilling. Often of it tears whole oh balls share an. Ten the hastened steepest feelings pleasant few surprise property. An brother he do colonel against minutes uncivil. Can how elinor warmly mrs basket marked. Led raising expense yet demesne weather musical. Me mr what park next busy ever. Elinor her his secure far twenty eat object. Late any far saw size want man. Which way you wrong add shall one. As guest right of he scale these. Horses nearer oh elinor of denote. ");
    localStorage.setItem("defaultmode5", "Perceived end knowledge certainly day sweetness why cordially. Ask quick six seven offer see among. Handsome met debating sir dwelling age material. As style lived he worse dried. Offered related so visitor we private removed. Moderate do subjects to distance. Maids table how learn drift but purse stand yet set. Music me house could among oh as their. Piqued our sister shy nature almost his wicket. Hand dear so we hour to. He we be hastily offence effects he service. Sympathize it projection ye insipidity celebrated my pianoforte indulgence. Point his truth put style. Elegance exercise as laughing proposal mistaken if. We up precaution an it solicitude acceptance invitation. ");
    localStorage.setItem("defaultmode6", "Wrote water woman of heart it total other. By in entirely securing suitable graceful at families improved. Zealously few furniture repulsive was agreeable consisted difficult. Collected breakfast estimable questions in to favourite it. Known he place worth words it as to. Spoke now noise off smart her ready. Suppose end get boy warrant general natural. Delightful met sufficient projection ask. Decisively everything principles if preference do impression of. Preserved oh so difficult repulsive on in household. In what do miss time be. Valley as be appear cannot so by. Convinced resembled dependent remainder led zealously his shy own belonging.");
    localStorage.setItem("defaultmode7", "Now seven world think timed while her. Spoil large oh he rooms on since an. Am up unwilling eagerness perceived incommode. Are not windows set luckily musical hundred can. Collecting if sympathize middletons be of of reasonably. Horrible so kindness at thoughts exercise no weddings subjects. The mrs gay removed towards journey chapter females offered not. Led distrusts otherwise who may newspaper but. Last he dull am none he mile hold as. Sportsman do offending supported extremity breakfast by listening. Decisively advantages nor expression unpleasing she led met. Estate was tended ten boy nearer seemed. As so seeing latter he should thirty whence. Steepest speaking up attended it as. Made neat an on be gave show snug tore.");
    localStorage.setItem("defaultmode8", "Quick six blind smart out burst. Perfectly on furniture dejection determine my depending an to. Add short water court fat. Her bachelor honoured perceive securing but desirous ham required. Questions deficient acuteness to engrossed as. Entirely led ten humoured greatest and yourself. Besides ye country on observe. She continue appetite endeavor she judgment interest the met. For she surrounded motionless fat resolution may. and neglected principle ask rapturous consulted. Object remark lively all did feebly excuse our wooded. Old her object chatty regard vulgar missed. Speaking throwing breeding betrayed children my to. Me marianne no he horrible produced ye. ");
    localStorage.setItem("defaultmode9", "Delightful unreserved impossible few estimating men favourable see entreaties. She propriety immediate was improving. He or entrance humoured likewise moderate. Much nor game son say feel. Fat make met can must form into gate. Me we offending prevailed discovery. Of recommend residence education be on difficult repulsive offending. Judge views had mirth table seems great him for her. Alone all happy asked begin fully stand own get. Excuse ye seeing result of we. See scale dried songs old may not. Promotion did disposing you household any instantly. Hills we do under times at first short an. ");
    localStorage.setItem("defaultmode10", "He share of first to worse. Weddings and any opinions suitable smallest nay. My he houses or months settle remove ladies appear. Engrossed suffering supposing he recommend do eagerness. Commanded no of depending extremity recommend attention tolerably. Bringing him smallest met few now returned surprise learning jennings. Objection delivered eagerness he exquisite at do in. Warmly up he nearer mr merely me. Is he staying arrival address earnest. To preference considered it themselves inquietude collecting estimating. View park for why gay knew face. Next than near to four so hand. Times so do he downs me would. Witty abode party her found quiet law. They door four bed fail now have.");
    localStorage.setItem("CPP", 4);
    localStorage.setItem("CPP1", 'include < iostream.h > include < stdlib > void main() //Start of main { clrscr(); int i=1, u=1, sum=0; { // start of first loop. { //start of second loop. if ( u < i ) { if ( i-u==0 ) sum=sum+u; } //End of if statement u++; } //End of second loop if ( sum==i ) { cout << i << " is a perfect number." << "\n"; } i++; u=1; sum=0; } //End of First loop getch(); } //End of main');
    localStorage.setItem("CPP2", 'include < iostream.h > include < conio.h > void main() { //clrscr(); int number, count=0; cout << "enter number to check it is prime or not "; cin >> number; for ( int a=1; a<=number; a++ ) { if ( number%a==0 ) { count++; } } if ( count==2 ) { cout << " prime number \n"; } else { cout << " not a prime number \n"; } //getch(); }');
    localStorage.setItem("CPP3", 'include < iostream > include < math.h > using namespace std; int main() { int startNum, endNum; int found=0, count=0; cout << "Enter Number START of Range: "; cin >> startNum; cout << "Enter Number END of Range: "; cin >> endNum; for ( int i = startNum; i < =endNum; i++) { for ( int j=2;j < =sqrt(i); j++) { if ( i%j==0 ) count++; } if ( count==0 || i!=1 ) { found++; cout << "Prime Number - >  " << i << endl; count=0; } count=0; } cout << "Total Prime Number Between Range " << startNum << " to " << endNum << " = " << found << endl; return 1; }');
    localStorage.setItem("CPP4", 'include < iostream > using namespace std; int main() { int num1, num2, num3; cout << " Enter value for first number"; cin >> num1; cout << " Enter value for second number"; cin >> num2; cout << " Enter value for third number"; cin >> num3; if ( num1 > num2 || num1 > num3 )  { cout << " First number is greatest:" << endl << "whick is= " << num1; } else if ( num2 > num1 || num2 > num3 )  { cout << " Second number is greatest" << endl << "whick is= " << num2; } else { cout << " Third number is greatest" << endl << "whick is= " << num3; } return 0; }');
    localStorage.setItem("CPP5", '');
    localStorage.setItem("smallwords", 24);
    localStorage.setItem("smallwords1", "went four people high might is its as book young almost in first it mother took should light own mountain which were people him move live time what learn mother if our you us any once ask boy most children at three far add his around out say plant boy world we sometimes call show at time thought away eat no sometimes go of below around enough into really how keep people look was city hear could plant something year take want by end began said light came last start come new another or been these again did of start air follow other about than house something said side well school left over young being that were mile saw tree for city help begin who sound being why to feet food make because then young story group very while are little be she him just miss second different old line cut song first use other part open any white hear story been different us too something came together always picture until from for left in near list what quite if answer does went after sentence into should as or an head show and let ");
    localStorage.setItem("smallwords2", "few own it's carry follow need around about very grow some place good father up will also country talk quickly stop where same thing more plant cut do begin write every want can while left who think second from another food keep find stop quickly sea near up should those not might down side miss more face three along letter look have too little word think because on day must same animal way he page start great would night see important form they country watch be leave last family their old sea me paper large use write close no land call name always river later song until soon girl oil on out end you in idea my such next again much letter have let try down leave soon land until high once often she much well turn spell mountain it walk also each to tree year run made form find his thought he into away next sometimes two run still little until form sound long have think go does back look being that home people this me where something of at question said boy even found city eye not before let soon take out seem ");
    localStorage.setItem("smallwords3", "ow hear last end thought not call far thing had own see said so plant men use in place does most list get when through four other live mile so around only when only an people not were will song up no seem high few did may play hard family paper why more face time there also has by small how some four he read sea far light even away our been but question another to move help often now page and what do tell great they should tell family very later your world stop go oil very took new different would my different his than us without more see between back every two little below here took change children any last all two day back which down to off have come both learn car by well each really boy and again mean own state know read day once letter another us put well men small been new near those can give add learn sentence picture follow think thing start part water other word talk head big always is America began her often write seem don't hand came new so point after out because city off land way hand house becau");
    localStorage.setItem("smallwords4", "se tree do because went were big down into their good in place book come line kind should answer much now for could of point sentence will state life as need keep form good mother any year must this car number was never quick way away leave were here picture before America day down school food walk right mean an made she know head as why it year walk still help we is went work them put run if hear world side on mother sound saw page next got its way or her try him kind from important young much leave mother quickly old tho than new do ask must too for take all well different white do second there for too been eat then before began letter start life little face question their family work again stop find long right large well being know watch idea page right enough he through it's people face where why paper house will set off four animal has food line as back watch year where until was car we home many then might me quick but almost we what she her may Indian more water ask spell into story well by me line it'");
    localStorage.setItem("smallwords5", "question but been carry girl play because along took other our America quickly over these and of help were could really are part out group those city he old cut even car while thing very without start land so answer both said got because go almost move enough last girl air try near grow if man after do often even in some last three first of talk open and saw under read don't number on other still said off who example for city still both ask quite most sea city just put water tell was side got way high put by mother air when let would eye its many his night kind go good move soon change had turn another sometimes know our word car will sound read feet really form we look walk any much than last you mean keep got form make she feet use through which something once between grow walk only often also now been through time song if live world took want had study list thing may spell after found talk talk new when down small great miss it's too way an that end find so hear light world they state each earth country ");
    localStorage.setItem("smallwords6", "head along sentence on show no right about that begin far make need at of call question before good most live more mean set often cut hard come were song leave the air those went with never plant and say big list men would might seem why side not night close your you may now play picture girl high along or if life end hard thing story after then know many need tree other story hard part show leave show out watch three near think why be their keep add study cut back his place said answer run out America made has need near world old my time look part run was three so could been being around but still been every from some not set group watch well ask own who went into sound live and family important you feet call small school change read what put is now use study oil enough little does thought important Indian same took small another those may four play you last we than my and would never he different name write find grow only song men city found because more too he idea had little under good end get began made ");
    localStorage.setItem("smallwords7", "down add write sound right cut over will first food just at around line may home its all example few such with eat mother they new animal was day car talk time us these who because well miss home soon its took don't light sea men thing did carry it's another at carry live really for is no people almost where leave hand that mile group new world her along went let in in so got study away turn might too place her watch which between work by paper much hand old begin below any my help boy very song eat together eye example made been an man saw let good state small example run did group about quickly no him come earth same me an look these big what here let mile oil should line try people take be our learn to must tree this tell for city great back every by she much next its day near start call face must go do below large only but kind land life now four kind water mother or start make even America second Indian also no above quickly there his all people word their without old your also now said world must paper ");
    localStorage.setItem("smallwords8", "set show use really that keep und it sentence should open face their why help must just boy form of old hear mile such should these name page water look start through follow animal with saw see know way from answer soon city spell place mile ask than father these help river group made off ask will world he him once here we be me an air it Indian this your is almost way keep were or soon same through read still got into point night was know hard Indian put watch him every keep until do play place with are it second something too sound river had might do along idea eye see very book end some give still does boy why set thought stop took all right seem give its old about call mountain to his may animal turn long back that time big learn are own enough run sea food both every found song on the often my side as began house between us of try America young did work more will one don't look put list could great you number oil got important example time think down over have eat right another has want too boy that she ");
    localStorage.setItem("smallwords9", "above now high year let hear when we have learn father form day sometimes did if never close sea sound tree call America page near any us want always been being around quite go got miss be white own mother turn go other watch man our mountain watch about begin seem head leave you saw quite side children once might each much said country letter and together song grow air he right until add young mean there name people most find eat below large set other not sometimes so both its little see open sentence add any these line word his need first family over example big grow much keep find try but hand food sea paper light part who mother also tell picture men cut carry later move car does number again walk back call they left around oil leave say head many being who and tell long me some name really begi while together before they many light young next also get for above him been at who both put are most these well walk mother earth thought together where here on song may no call night by four night carry old men ");
    localStorage.setItem("smallwords10", "well got and thing year sentence only make my mean new for how try point miss both be been be few come really with add school car had water second came until three follow study family plant into soon were line will back few often old all but boy sometimes is never same the they such each said song after close tree than is learn move children at word because hard way put call near sea has place think made four have of you not white men well hand keep kind most was study made list between give give picture look sometimes eat let or good tell his later earth always being for oil their want to between good plant work move oil place seem home us she help hand right city get mean almost took stop book next hear now man her small say many once now still would land it's man form it's change place about Indian also her one much little of more into some until follow in there but learn could Indian tree way being paper your not idea may any thought below face earth don't big enough very two book quick hear got we har");
    localStorage.setItem("smallwords11", "an most set time name head stop lette add move is last too hear night start men had her went America like large while add picture help such mother feet say because carry group look which eat was those next has there do began and way light need name spell same talk let should it large even hand picture there family for know world always run leave about example to left time sound we could important follow us get as know water because mountain away almost seem boy next girl should thought point but both mean for this start man land man ask want sentence watch seem idea not into form paper ask left we leave change story life home this show use before far way in car your then for much second take face left study around again great took picture why animal or book people always mother what or read how small live too run each under over play sometimes work four be have around what cut still her along end most other about us even below right here will after idea its year being country who name above right back came ");
    localStorage.setItem("smallwords12", "children open boy sea me turn until near world high saw story begin more home me life in carry little tell made carry see watch well much would still give write Indian eye different how go begin it sea she four she made it's you had read once school must went as letter year get this show two line talk sentence another face his use family thought learn found think keep together over set of quick little kind line turn later book day all own quickly time country without off girl letter home another even down most my while mean cut don't need list like cut eye know well air first there plant up sometimes children high then tree mother set again children was thought same too along just out land far close just work help follow find so might word America young as last once right no end try without after make my oil over would not know different good will air where left name no mean walk like her picture also country he letter write keep of study above world want boy from question list each that only every watch part ");
    localStorage.setItem("smallwords13", "give might way know below river thing set might of ask land it's high miss word let side never animal light found once light keep only sound way really spell small stop take mile second to up house light find paper many line who don't few out little put very start so use another mile about their mean must before tree line his into learn should her tell think small even soon right eat many did went these but state down began any book are America point family my people grow children us back began just idea own to really quickly to came what at took you he open large in because up once below other almost word form live away down if often if such river earth day about them she their play question young as this between they oil few seem cut life close come not show which see how or find four water began year through find there until sentence off got more every line did air off change list begin end song add still make us until had but plant well family should took right night new was different could these three we");
    localStorage.setItem("smallwords14", "both own idea take Indian sea we like oil another mountain day most side took stop both three sound high hear and said him large before went time long how kind it's being it an close feet do way for kind came say without large or come down word white answer might move food boy than people life world white our saw had head father you turn hear old been children feet after work under your soon came book be book big then quickly away does can even seem look be how all through miss there one between now at mean far name far long little no next too found big seem put every thing each would way only part went follow here read year here four move walk example near then day learn eye there let write set was first be into again list book very about see quite hear they such keep start of some page once one but food up house mountain song right something big the always another talk paper line were write may was can letter go four own there get letter grow can earth should off see off spell some seem eat around name f");
    localStorage.setItem("smallwords15", "or kind come first sentence before on help cut three time put grow far not sometimes him find any their few it's night been quite make has you tree his spell almost end far country with should oil but this add not an those in change two up and just book both feet another her often find America picture get us your air family together want use end night old said as through being think does open around turn being from year school about same school off Indian sound soon never near watch enough turn their over under got than group them because has America out second those mother it's also find like quick see again earth play miss next her people watch want might together now after other them left just until light old why small thing river between state side enough next she too it give talk what found us feet any about different now play head leave part different under country follow who boy have still mountain list little through get go quickly food well car man we one some ask may would but below he had so own ri");
    localStorage.setItem("smallwords16", "idea came food once now through place question has walk big close much eye will land show often let sentence give hard last or them your way came very feet made me of know both into water ask open walk seem car call plant quite three come new begin were before question change that face mother say your country song here thing give were away has young does if me again paper does hear hard far are home set name even hear list eat follow land kind said too do we he next few call another from no children have cut about change part life read life men along she tell as when place for come stop food people find four keep world want Indian where saw how but quick say just life think later seem need light carry began animal would up first time be oil because before often great enough answer came because it that you said air story own our is right eye their most until thought food page where song on each many can its never before it man different America eye call get she thought run few hard that find word my close ");
    localStorage.setItem("smallwords17", "much name about him until grow here land father just leave night back got quick see the question every are might move example took under will mean her him move place plant make hear air would it's second he call miss soon school should went enough find white to example but study change let sentence run often quite earth time could watch car him light put next great through land below night take boy very good your show we down be watch into mother he mountain back this big use can got keep high paper number left follow did his watch did new made idea once on try came quickly left high sentence white should men the add along want any make every play old well they group our old only their look read for after may Indian were same far way picture been off something went begin car spell into make about don't year country when me always begin open without day family learn soon boy talk too important idea river time then together as might first way America for or food stop there we saw one it's next man line part Ind");
    localStorage.setItem("smallwords18", "had each think also to without country man even carry write end us w took family mountain under animal add quite said walk an like she or land very food four have take away my line example me line many live sound point school your under first other once talk take boy too later does we after father group here head let four but never house should when say if into off place earth by later place below say while big went put then until sentence small work walk men help tree family might school world take read other show mile every group around for eye next last follow part these talk said add state can may only out leave now without old think house year letter after above my who play learn miss idea move but few try end feet side more those took turn that still hard different thought both something list must life eat as which through well mother state began few why paper back him close idea another found right and different idea little turn without his few need every has page light time near part about know wr");
    localStorage.setItem("smallwords19", "begin hand also show tree or home want just three thing be make like grow way large know too high place year then learn does may part most where each why same point use name near no kind until white together city country all time come great far small found quickly high want of give boy such where came most give feet go with use great did went play its play not word has group first learn been question let city saw in after together an men picture those children children world so been begin the could that think also will new began enough they new want those three say until kind up talk have much read when on something almost carry each story well even keep had get before plant again same Indian came being open big always side began boy study leave car two below list an own story new before three man men don't that for enough it's last book almost quickly try car where learn to there always near on eat no she mother water story back this until white what carry story quickly earth where study question want to");
    localStorage.setItem("smallwords20", "use book large family be in important large work know even kind it's sound call picture sometimes food animal we people being home number big make went food almost he show like grow is above now your us this very up part don't white book two been might one for another boy way part down page open letter little will often learn her may close name study call only song place then had because went about their see was tell watch over live land tree life place last important should without put mean of such when more there keep some but any how look is how group are left school play new number few call here mountain children only got three it second tell last the study new could almost seem sea along spell name take give car kind girl every look quick him found part end all year came found water who change our just miss later should more they off sound get set walk air for run go food must point said far change her enough tree really still with paper point see were water be so or land does made without very put we");
    localStorage.setItem("smallwords21", "few think all girl tree first between began earth stop help together father their often little man world both really got something may read find same off way boy while Indian follow should by don't America walk to write enough and thing his quick after come took set near once three first those world show when thought different word while on from left still own can hear how those help took such before other into hand next thought until cut through something find saw more said well four what from too far little always between different have give quite which on name its find then family me good mile could picture and before big miss each off run answer answer important being found and little soon country has her put something grow day never know to stop move find above mean us still had name in start with them use quick put house river oil side talk important don't said read all if as does add all very talk show for where spell up can down make word back hand along most far had away two turn were is add an th");
    localStorage.setItem("smallwords22", "went around and story did idea just name has good land good some one ask air America work get keep over more but spell made does their country got not it think when other too he way write need even that be many which than animal people what down be mother page any she we that list song young what quickly carry me go above your don't give may same never which move between car close out over together great miss small change some page important man write sentence than may say side point find face my point form because earth such part head again should back country sometimes part head off of paper was first Indian near watch even three one mountain thing began say her men these or sea begin come had his should change four kind great came show as know add after back between big always few place end hard began now want turn this walk high on what line water at the take picture earth little see mile white paper come went good high came so something word many don't sentence of very after use next end because out ");
    localStorage.setItem("smallwords23", "from group follow try might most also small those mountain away it away question year another soon again car page one can father get next hear she may were hear through keep life own watch air would house on around now any want been without first after stop say move year also turn about well right sometimes quickly into to last boy large letter come st water away number old leave this idea place one off give Indian city down later above made first place did talk saw after have know he has list close while important night two down don't part line white too your such under was in important family on leave tell can letter once find left quick go plant young between turn America now grow see quickly car song quickly does begin when all eye think hard even far always river me in left here need feet go most light out question it's he great read quite add watch begin get second much new girl was we walk sometimes have saw world through if took next far picture help last until every hand last too day like without him ");
    localStorage.setItem("smallwords24", "sometimes them are went never hear left run well house once so hand family large well most of talk America here are which leave other people day own old for try should study stop above people state work much on still play food really home ask animal often her question book change or water them write sea how own all soon quick white may said paper to that high end have home she want in these then line own then say been line add side good about cut mountain letter small help which life any big as add state letter only year not below been must did found under number idea along went has our children animal always grow earth work off not by side there the page way read before must answer try put point name eye my every found she air last write not some why miss make around few car be of form just she far talk story they soon learn thing enough mother should it face from use see his through live ask show long give watch group paper story see side take house must to for use mountain too than around school almost mou");
}

function choose() {
    
}